#!/usr/bin/env python3
"""Turn the research bibliography into the file research.html reads.

    python3 code/build_research_data.py

Reads assets/data/research.json (the hand-maintained bibliography) and writes
assets/data/research-data.js, which assigns one object to window.ERN_RESEARCH.

It is a plain script rather than JSON fetched at runtime because a browser
gives every file:// document its own opaque origin and blocks same-directory
fetches. A <script src> is exempt, so the library works both on the live site
and when the page is opened straight off disk.

Labels for states and publication types are resolved here rather than in the
browser so the page carries no naming rules of its own.

The script also checks the publication count printed in research.qmd against
the bibliography and complains if the two have drifted.
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "data" / "research.json"
OUT = ROOT / "assets" / "data" / "research-data.js"
QMD = ROOT / "research.qmd"

TYPE_LABELS = {
    "academic": "Academic",
    "report": "Report",
    "working-paper": "Working paper",
    "dataset": "Dataset",
    "news": "News",
    "book": "Book",
}

# Words that keep their own casing when a state name is title-cased.
KEEP = {"d.c.": "D.C.", "of": "of"}


def state_label(value):
    """Short form, for the tag printed on every entry."""
    if value == "national":
        return "National"
    return " ".join(KEEP.get(w, w.capitalize()) for w in value.split())


def state_option(value):
    """Long form, for the filter menu, where the distinction has to be spelled
    out because there is nothing else on screen to read it against."""
    return "National (not state-specific)" if value == "national" else state_label(value)


def sort_key(item):
    # Newest first, undated last, then alphabetical inside a year.
    year = item.get("year")
    return (0 if year else 1, -(year or 0), (item.get("title") or "").lower())


def main():
    raw = json.loads(SRC.read_text(encoding="utf-8"))
    items = raw.get("items", [])

    problems = []
    for i, it in enumerate(items):
        if not (it.get("title") or "").strip():
            problems.append(f"item {i} has no title")
        if not (it.get("url") or "").strip():
            problems.append(f"item {i} ({it.get('title')!r}) has no url")
        if it.get("type") and it["type"] not in TYPE_LABELS:
            problems.append(f"item {i} has unknown type {it['type']!r}")

    titles = {}
    for it in items:
        key = (it.get("title") or "").strip().lower()
        titles.setdefault(key, []).append(it)
    dupes = {k: v for k, v in titles.items() if len(v) > 1}

    declared = raw.get("count")
    if declared is not None and declared != len(items):
        problems.append(
            f"research.json says count: {declared} but carries {len(items)} items"
        )

    clean = []
    for it in sorted(items, key=sort_key):
        clean.append(
            {
                "title": (it.get("title") or "").strip(),
                "authors": (it.get("authors") or "").strip(),
                "year": it.get("year"),
                "venue": (it.get("venue") or "").strip(),
                "type": it.get("type") or "",
                "typeLabel": TYPE_LABELS.get(it.get("type"), it.get("type") or ""),
                "state": it.get("state") or "",
                "stateLabel": state_label(it["state"]) if it.get("state") else "",
                "url": (it.get("url") or "").strip(),
            }
        )

    states = sorted({(i["state"], state_option(i["state"])) for i in clean if i["state"]})
    # National first, then the states alphabetically.
    states.sort(key=lambda s: (s[0] != "national", s[1]))

    payload = {
        "built_by": "code/build_research_data.py",
        "source": "assets/data/research.json",
        "updated": raw.get("updated"),
        "count": len(clean),
        "types": [
            {"value": v, "label": TYPE_LABELS[v]}
            for v in ("academic", "report", "working-paper", "dataset", "news", "book")
            if any(i["type"] == v for i in clean)
        ],
        "states": [{"value": v, "label": lb} for v, lb in states],
        "items": clean,
    }

    OUT.write_text(
        "/* Generated by code/build_research_data.py from assets/data/research.json.\n"
        "   Do not edit by hand: edit the JSON and rerun the script. */\n"
        "window.ERN_RESEARCH = " + json.dumps(payload, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )

    # The count is printed in prose on the page, so it has to be kept in step.
    stated = None
    if QMD.exists():
        m = re.search(r"count_in_prose:\s*(\d+)", QMD.read_text(encoding="utf-8"))
        if m:
            stated = int(m.group(1))
    if stated is not None and stated != len(clean):
        problems.append(
            f"research.qmd count_in_prose is {stated} but the library holds {len(clean)}"
        )

    # Report is the point of the run, so it is a return value, not chatter.
    report = {
        "written": str(OUT.relative_to(ROOT)),
        "items": len(clean),
        "states": len(states),
        "duplicate_titles": sorted(dupes),
        "problems": problems,
    }
    sys.stdout.write(json.dumps(report, indent=2) + "\n")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
